spring:
  data:
    mongodb:
      host: localhost              # MongoDB server hostname or IP address
      port: 27017                  # MongoDB server port
      database: app1               # Name of the MongoDB database
      username: app_root           # MongoDB username (if authentication is enabled)
      password: app_r00t           # MongoDB password (if authentication is enabled)

workflow:
  enable: true
