spring:
  datasource:
    url: jdbc:mysql://gateway01.ap-southeast-1.prod.aws.tidbcloud.com:4000/test
    username: 333kDHq9cR41YDy.root
    password: THo0vN1V3k29xaGm
    driver-class-name: com.mysql.cj.jdbc.Driver

workflow:
  enable: true
