spring:
  data:
    mongodb:
      uri: mongodb+srv://<user>:<password>@<host>/?retryWrites=true&w=majority
      database: app1
workflow:
  enable: true
  thread-pool-size: 10
  definitions:
    - definitions/HelloWorkflow.json

logging:
  level:
    org.springframework: INFO
